### ISSUE TITLE
Using blobFromImage with OpenCV 3.4.1 causes Fatal error

### ISSUE THREAD

**Issue by Jeppelelle** [php-opencv/php-opencv#11]
I am using branch 3.4 of php-opencv & i am using OpenCV 3.4.1, the installation worked fine and this example works:

```
use CV\CascadeClassifier, CV\Scalar;
use function CV\{imread, imwrite, cvtColor, equalizeHist, rectangleByRect};
use const CV\{COLOR_BGR2GRAY};
$src = imread("temp/lol2.png");
$gray = cvtColor($src, COLOR_BGR2GRAY);
// face by lbpcascade_frontalface
$faceClassifier = new CascadeClassifier();
$faceClassifier->load('models/lbpcascades/lbpcascade_frontalface.xml');
$faceClassifier->detectMultiScale($gray, $faces);
//var_export($faces);
if ($faces) {
    $scalar = new Scalar(0, 0, 255); //blue
    foreach ($faces as $face) {
        rectangleByRect($src, $face, $scalar, 3);
    }
}

else {
	echo 'face not detected';
}

imwrite("temp/_detect_face_by_cascade_classifier.png", $src);
```

But non of the examples that is using blobFromImage is working, like this one:

```
use CV\Scalar;
use function CV\{imread, cvtColor};
$categories = explode("\n", file_get_contents('models/mobilenet/classes.txt'));
$src = imread("temp/cat.jpg"); // opencv loads image to matrix with BGR order
$src = cvtColor($src, CV\COLOR_BGR2RGB); // convert BGR to RGB
//var_export($src);
$blob = \CV\DNN\blobFromImage($src, 0.017, new \CV\Size(224,224), new Scalar(103.94, 116.78, 123.68)); // convert image to 4 dimensions matrix
//var_export($blob);
$net = \CV\DNN\readNetFromCaffe('models/mobilenet/mobilenet_deploy.prototxt', 'models/mobilenet/mobilenet.caffemodel');
$net->setInput($blob, "");
$r = $net->forward();
//var_export($r);
$maxConfidence = 0;
$confidences = [];
for ($i = 0; $i < 1000; $i++) {
    $confidences[$i] = intval($r->atIdx([0,$i,0,0], 1) * 100);
}
// top 5:
arsort($confidences);
$confidences = array_slice($confidences, 0, 5, true);
foreach ($confidences as $label => $confidence) {
    echo "$confidence%: {$categories[$label]}\n";
}
```

The last one will give me the error "**Fatal error: Uncaught Error: Call to undefined function CV\DNN\blobFromImage() in...**"

The installation went fine so everything should be working, but nope, blobFromImage is not working, always gives me an error. Would be nice to get object detection to work, so anyone got any tips on where i should start troubleshooting? I would really appreciate it

**Comment by morozovsk** [comment]
change from:
> $src = imread("temp/cat.jpg"); //null

to:

> $src = imread("images/cat.jpg");

**Comment by Jeppelelle** [comment]
Thanks for the reply but i've changed the folder structure in my project so "temp/cat.jpg" is correct path for me.

Everyone of the examples works except for those who uses DNN.

I still have not managed to get it to work on Ubuntu 18.04.2, i spent several days to try to get it to work, i checked all dependencies, made sure i had no errors with "make test" after compiling in both opencv and php-opencv, no errors.

I installed Debian 10 and got it to work with no problem at all though, which is weird because i have the exact same packages in both environments (clean install in both Ubuntu & Debian).

I guess i just use Debian instead since it works there.

**Comment by morozovsk** [comment]
OpenCV 3.4.1 is old and branch 3.4 is old.
You can try install opencv4 on Ubuntu 18.04 from packages without compilation:
https://github.com/php-opencv/php-opencv/wiki/Installation
