### ISSUE TITLE
Can't compile on Debian 10

### ISSUE THREAD

**Issue by jackyhallyday** [php-opencv/php-opencv#16]
Hi,

I tried to install php-opencv on a my Debian 10, but it won't compile because of this error:

`/root/php-opencv/source/opencv2/core/opencv_mat.cc: In function ‘void opencv_mat_init()’:
/root/php-opencv/source/opencv2/core/opencv_mat.cc:858:49: error: invalid conversion from ‘void (*)(zval*, zval*, zval*, void**)’ {aka ‘void (*)(_zval_struct*, _zval_struct*, _zval_struct*, void**)’} to ‘zend_object_write_property_t’ {aka ‘_zval_struct* (*)(_zval_struct*, _zval_struct*, _zval_struct*, void**)’} [-fpermissive]
     opencv_mat_object_handlers.write_property = opencv_mat_write_property;
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:194: source/opencv2/core/opencv_mat.lo] Error 1`

**Comment by morozovsk** [comment]
Hi,
It works only with PHP 7.0 / 7.1 / 7.2 and OpenCV 4.0.0+
What version do you use?

**Comment by jackyhallyday** [comment]
Oooooh, ok. I installed OpenCV 4.3 but I'm using PHP 7.4.
Thanks for your answer, I looked at the requirements for the OpenCV version and just had a glance at the PHP requirement. I saw 7 dot....and I assumed any version above that would work. My bad.

**Comment by morozovsk** [comment]
now php-opencv supports php 7.4 / 8.0

**Comment by ssada1975** [comment]
still same error with php 8.2. How to solve?

root@brandiving_f14bf9accb:/home/php-opencv# make
/bin/bash /home/php-opencv/libtool --tag=CXX --mode=compile g++ -I. -I/home/php-opencv -I/home/php-opencv/include -I/home/php-opencv/main -I/home/php-opencv -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/opencv4  -DHAVE_CONFIG_H  -g -O2   -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -DZEND_COMPILE_DL_EXT=1 -c /home/php-opencv/opencv.cc -o opencv.lo  -MMD -MF opencv.dep -MT opencv.lo
 g++ -I. -I/home/php-opencv -I/home/php-opencv/include -I/home/php-opencv/main -I/home/php-opencv -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/opencv4 -DHAVE_CONFIG_H -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -DZEND_COMPILE_DL_EXT=1 -c /home/php-opencv/opencv.cc -MMD -MF opencv.dep -MT opencv.lo  -fPIC -DPIC -o .libs/opencv.o
/bin/bash /home/php-opencv/libtool --tag=CXX --mode=compile g++ -I. -I/home/php-opencv -I/home/php-opencv/include -I/home/php-opencv/main -I/home/php-opencv -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/opencv4  -DHAVE_CONFIG_H  -g -O2   -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -DZEND_COMPILE_DL_EXT=1 -c /home/php-opencv/source/opencv2/core/opencv_mat.cc -o source/opencv2/core/opencv_mat.lo  -MMD -MF **source/opencv2/core/opencv_mat.dep -MT source/opencv2/core/opencv_mat.lo
/home/php-opencv/libtool: line 1290: source/opencv2/core/opencv_mat.loT: No such file or directory
mkdir source/opencv2/core/.libs
mkdir: cannot create directory 'source/opencv2/core/.libs': No such file or directory
make: *** [Makefile:213: source/opencv2/core/opencv_mat.lo] Error 1**
