### ISSUE TITLE
Update to use with PHP 8.1 and prepare for 8.1

### ISSUE THREAD

**Issue by tacman** [php-opencv/php-opencv#43]
Are there plans to update this extension for PHP 8.1?  Also, PHP 8.2 comes out next month, it'd be great to see that as well.

Although I'm interested in this for a hobby project (that is, unfunded), I might be able to contribute some money toward development.  Send me a private message if you'd like, tacman@gmail.com

**Comment by morozovsk** [comment]
hello. now php-opencv supports php8.1 and php8.2.

docker file for 8.1: https://github.com/php-opencv/php-opencv-examples/blob/master/docker/ubuntu-22.04_php-8.1_opencv-4.5.0/Dockerfile
docker file for 8.2 https://github.com/php-opencv/php-opencv-examples/blob/master/docker/ubuntu-22.04_php-8.2_opencv-4.5.0/Dockerfile

built packages: https://github.com/php-opencv/php-opencv-packages

actually php-opencv was working for php-8.1 and php-8.2. I just fixed couple tests and compiled it without problems.
