### ISSUE TITLE
PHP Fatal error: Internal zvals cannot be refcounted 

### ISSUE THREAD

**Issue by walterpadua** [php-opencv/php-opencv#44]
I compiled php-opencv on 3 different php versions php-8, php-8.1, php-8.2, and on 3 versions for some random reason the PHP Fatal error: Internal zvals cannot be refcounted.

**Comment by morozovsk** [comment]
usually you can see error like "PHP Fatal error: Internal zvals cannot be refcounted." when you checkout from php7 branch but try to compile for php8.

now master branch is for php8.2.

you can see how to compile in examples:

docker file for 8.1: https://github.com/php-opencv/php-opencv-examples/blob/master/docker/ubuntu-22.04_php-8.1_opencv-4.5.0/Dockerfile
docker file for 8.2 https://github.com/php-opencv/php-opencv-examples/blob/master/docker/ubuntu-22.04_php-8.2_opencv-4.5.0/Dockerfile
