### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by kimia000** [php-opencv/php-opencv#8]
When running classify_image_by_dnn_mobilenet.php from the examples, if using a larger model (than the one provided)

`$net = \CV\DNN\readNetFromCaffe('deploy.prototxt', 'caffenet.caffemodel');
`
the script terminates at 

`$r = $net->forward();`

with the error:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

which I believe is memory-related. How is the memory used by the underlying C++ process is limited, and how to lift this limit?

**Comment by morozovsk** [comment]
By default php (not a C++ process) is limited:
memory_limit	"128M"
Did you change memory_limit in php.ini?

**Comment by Nidiots** [comment]
Hi 
  i got the same issue , trying to use this in laravel , any solution. memory  limit increased to 1GB .
Its working fine when i run it from same folder.
